version = 1

exclude_patterns = [
  "docker/resources/**",
  "**/MyVisualEditor/**",
  "frontend/public/**",
  "node_modules/"
]

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "docker"

[analyzers.meta]
dockerfile_paths = [
  "frontend/Dockerfile"
]

[[analyzers]]
name = "javascript"

[analyzers.meta]
plugins = ["vue"]
environment = [
  "nodejs",
  "browser"
]

[[analyzers]]
name = "test-coverage"
enabled = true