version = 1

exclude_patterns = [
  "mediawiki/**",
  "MyVisualEditor/**",
  "MyPureVisualEditor/**",
  "frontend/public/**",
  "node_modules/"
]

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "docker"

  [analyzers.meta]
  dockerfile_paths = [
    "backend/Dockerfile",
    "frontend/Dockerfile"
  ]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["vue"]
  environment = [
    "nodejs",
    "browser"
  ]