version = 1

exclude_patterns = [
  "mediawiki/**",
  "frontend/public/**"
]

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["vue"]
  environment = [
    "nodejs",
    "browser"
  ]