services:
  wikiadviser-caddy:
    image: wikiadviser-caddy:git
    container_name: wikiadviser-caddy
    volumes:
      - caddy-data:/data
      - ./Caddyfile.dev:/etc/caddy/Caddyfile:ro
      - /var/log/caddy/:/var/log/caddy/
    build:
      context: frontend
      args:
        SUPABASE_PROJECT_URL: ${SUPABASE_PROJECT_URL}
        SUPABASE_SECRET_PROJECT_TOKEN: ${SUPABASE_SECRET_PROJECT_TOKEN}
        MEDIAWIKI_ENDPOINT: ${MEDIAWIKI_ENDPOINT}
        WIKIADVISER_LANGUAGES: ${WIKIADVISER_LANGUAGES}
        SHARE_LINK_DAY_LIMIT: ${SHARE_LINK_DAY_LIMIT}
        SENTRY_DSN_FRONTEND: ${SENTRY_DSN_FRONTEND}
        SENTRY_ENV_FRONTEND: ${SENTRY_ENV_FRONTEND}
        POSTHOG_API_KEY: ${POSTHOG_API_KEY}
        POSTHOG_API_HOST: ${POSTHOG_API_HOST}
        X_API_KEY: ${X_API_KEY}
    ports:
      - 9000:9000
    environment:
      - WIKIADVISER_FRONTEND_ENDPOINT=${WIKIADVISER_FRONTEND_ENDPOINT}
      - WIKIADVISER_LANGUAGES=${WIKIADVISER_LANGUAGES}
      - SENTRY_DSN_FRONTEND=${SENTRY_DSN_FRONTEND}
      - SENTRY_ENV_FRONTEND=${SENTRY_ENV_FRONTEND}
      - POSTHOG_API_KEY=${POSTHOG_API_KEY}
      - POSTHOG_API_HOST=${POSTHOG_API_HOST}
      - SHARE_LINK_DAY_LIMIT=${SHARE_LINK_DAY_LIMIT}
      - SUPABASE_PROJECT_URL=${SUPABASE_PROJECT_URL}
      - X_API_KEY=${X_API_KEY}
      - MEDIAWIKI_INTERNAL_ENDPOINT=${MEDIAWIKI_INTERNAL_ENDPOINT}

volumes:
  caddy-data:
