version: "3.1"

services:
  wikiadviser-api:
    image: wikiadviser-api:git
    restart: on-failure
    container_name: wikiadviser-api
    build:
      context: backend
    env_file:
      - .env
    ports:
      - 127.0.0.1:${WIKIADVISER_API_PORT}:${WIKIADVISER_API_PORT}

  wikiadviser-caddy:
    image: wikiadviser-caddy:git
    container_name: wikiadviser-caddy
    volumes:
      - caddy-data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./robots.txt:/etc/caddy/robots.txt:ro
    build:
      context: frontend
      args:
        WIKIADVISER_API_ENDPOINT: ${WIKIADVISER_API_ENDPOINT}
        SUPABASE_PROJECT_URL: ${SUPABASE_PROJECT_URL}
        SUPABASE_SECRET_PROJECT_TOKEN: ${SUPABASE_SECRET_PROJECT_TOKEN}
        MEDIAWIKI_ENDPOINT: ${MEDIAWIKI_ENDPOINT}
        WIKIADVISER_HOST: ${WIKIADVISER_HOST}
    ports:
      - 443:443
      - 80:80
    environment:
      - WIKIADVISER_API_PORT=${WIKIADVISER_API_PORT}
      - WIKIADVISER_FRONTEND_ENDPOINT=${WIKIADVISER_FRONTEND_ENDPOINT}    
      - WIKIADVISER_BACKEND_ENDPOINT=${WIKIADVISER_BACKEND_ENDPOINT}    

    depends_on:
      - wikiadviser-api

volumes:
  caddy-data:
