version: "3.1"

services:
  wikiadviser-api:
    image: wikiadviser-api:git
    container_name: wikiadviser-api
    build:
      context: backend
    env_file:
      - .env
    ports:
      - 8021:${WIKIADVISER_API_PORT}

  wikiadviser-caddy:
    image: wikiadviser-caddy:git
    container_name: wikiadviser-caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    build:
      context: frontend
      args:
        WIKIADVISER_API_HOST: ${WIKIADVISER_API_HOST}
        SUPABASE_PROJECT_URL: ${SUPABASE_PROJECT_URL}
        SUPABASE_SECRET_PROJECT_TOKEN: ${SUPABASE_SECRET_PROJECT_TOKEN}
        MEDIAWIKI_HOST: ${MEDIAWIKI_HOST}
    ports:
      - 443:443
      - 80:80
    depends_on:
      - wikiadviser-api
