# MediaWiki with MARIADB
services:
  mediawiki:
    build:
      dockerfile: ./Dockerfile
    networks:
      - docker_network
    ports:
      - 8080:${MW_PORT}
    volumes:
      - ./MW_CREDENTIALS.txt:/wikiadviser/mediawiki-setup/MW_CREDENTIALS.txt
      - ./conf/php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini
      - ./resources/extensions/MyVisualEditor:/var/www/mediawiki/wiki/en/extensions/MyVisualEditor
      - init-data:/data

    depends_on:
      - mediawiki_db


  mediawiki_db:
    image: mariadb:11.4
    restart: always
    networks:
      - docker_network
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

    volumes:
      - mw-data:/var/lib/mysql

networks:
  docker_network:
    driver: bridge

volumes:
  init-data:
  mw-data:
