# Mediawiki + Wikiadviser
services:
  mediawiki:
    container_name: mediawiki
    image: ankabootops/mediawiki:1.45.0-wmf.9
    networks:
      - docker_network
    ports:
      - 8080:${MW_PORT}
    volumes:
      - ./MW_CREDENTIALS.txt:/wikiadviser/mediawiki-setup/MW_CREDENTIALS.txt
      - ./conf/php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini
      - ./resources/extensions/MyVisualEditor:/var/www/mediawiki/wiki/en/extensions/MyVisualEditor
      - init-data:/data
    depends_on:
      - mediawiki_db
    entrypoint: ./docker-entrypoint.sh
    command: apache2-foreground
    healthcheck:
      test: ["CMD-SHELL", "test -f /wikiadviser/mediawiki-setup/.setup_complete || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  mediawiki_db:
    image: mariadb:11.4
    restart: always
    networks:
      - docker_network
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

    volumes:
      - mw-data:/var/lib/mysql

  wikiadviser-caddy:
    container_name: wikiadviser-caddy
    volumes:
      - caddy-data:/data
      - ./conf/Caddyfile.dev:/etc/caddy/Caddyfile:ro
      - /var/log/caddy/:/var/log/caddy/
    build:
      context: ../frontend
      args:
        SUPABASE_PROJECT_URL: ${SUPABASE_PROJECT_URL}
        SUPABASE_SECRET_PROJECT_TOKEN: ${SUPABASE_SECRET_PROJECT_TOKEN}
        MEDIAWIKI_ENDPOINT: ${MEDIAWIKI_ENDPOINT}
        WIKIADVISER_LANGUAGES: ${WIKIADVISER_LANGUAGES}
        # SHARE_LINK_DAY_LIMIT: ${SHARE_LINK_DAY_LIMIT}
        # SENTRY_DSN_FRONTEND: ${SENTRY_DSN_FRONTEND}
        # SENTRY_ENV_FRONTEND: ${SENTRY_ENV_FRONTEND}
        # POSTHOG_API_KEY: ${POSTHOG_API_KEY}
        # POSTHOG_API_HOST: ${POSTHOG_API_HOST}
        X_API_KEY: ${X_API_KEY}
    network_mode: "host"
    environment:
      - WIKIADVISER_FRONTEND_ENDPOINT=${WIKIADVISER_FRONTEND_ENDPOINT}
      - WIKIADVISER_LANGUAGES=${WIKIADVISER_LANGUAGES}
      # - SENTRY_DSN_FRONTEND=${SENTRY_DSN_FRONTEND}
      # - SENTRY_ENV_FRONTEND=${SENTRY_ENV_FRONTEND}
      # - POSTHOG_API_KEY=${POSTHOG_API_KEY}
      # - POSTHOG_API_HOST=${POSTHOG_API_HOST}
      # - SHARE_LINK_DAY_LIMIT=${SHARE_LINK_DAY_LIMIT}
      - SUPABASE_PROJECT_URL=${SUPABASE_PROJECT_URL}
      - X_API_KEY=${X_API_KEY}
      - MEDIAWIKI_HOST=${MEDIAWIKI_HOST}
      - SUPABASE_SECRET_PROJECT_TOKEN=${SUPABASE_SECRET_PROJECT_TOKEN}
      - MEDIAWIKI_REVERSE_PROXY_ENDPOINT=${MEDIAWIKI_REVERSE_PROXY_ENDPOINT}
      - MEDIAWIKI_ENDPOINT=${MEDIAWIKI_ENDPOINT}

networks:
  docker_network:
    driver: bridge

volumes:
  init-data:
  mw-data:
  caddy-data:
