name: Run CI checks
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/**"

jobs:
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      actions: ${{ steps.filter.outputs.actions }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
            actions:
              - '.github/workflows/**'

  frontend:
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' || needs.changes.outputs.actions == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"
      - name: Install dependencies
        run: cd frontend && pnpm install
      - name: Check linting
        run: cd frontend && pnpm run lint
      - name: Check formatting
        run: cd frontend && pnpm run prettier
