name: Run CI checks
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/**"

jobs:
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
      actions: ${{ steps.filter.outputs.actions }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'
            actions:
              - '.github/workflows/**'

  backend:
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' || needs.changes.outputs.actions == 'true'  }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"
      - name: Install dependencies
        run: cd backend && pnpm install --frozen-lockfile
      - name: Check linting
        run: cd backend && pnpm run lint
      - name: Check formatting
        run: cd backend && pnpm run prettier
      - name: Run test coverage
        run: cd backend && pnpm run test:coverage
      - name: Report results to DeepSource
        run: |
          curl https://deepsource.io/cli | sh
          ./bin/deepsource report --analyzer test-coverage --key javascript --value-file ./backend/coverage/cobertura-coverage.xml
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
      - name: NPM Audit & Comment
        uses: JamesRobertWiseman/pnpm-audit@v1.0.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: critical
          fails: true

  frontend:
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' || needs.changes.outputs.actions == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"
      - name: Install dependencies
        run: cd frontend && pnpm install --frozen-lockfile
      - name: Check linting
        run: cd frontend && pnpm run lint
      - name: Check formatting
        run: cd frontend && pnpm run prettier
      - name: NPM Audit & Comment
        uses: JamesRobertWiseman/pnpm-audit@v1.0.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: critical
          fails: true
