name: Run CI checks on Push
on:
  push:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: cd backend && npm ci
      - name: Check linting
        run: cd backend && npm run lint
      - name: Check formatting
        run: cd backend && npm run prettier
      - name: Run test coverage
        run: cd backend && npm run test:coverage
      - name: Report results to DeepSource
        run: |
          curl https://deepsource.io/cli | sh
          ./bin/deepsource report --analyzer test-coverage --key javascript --value-file ./backend/coverage/cobertura-coverage.xml
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: cd frontend && npm ci
      - name: Check linting
        run: cd frontend && npm run lint
      - name: Check formatting
        run: cd frontend && npm run prettier
