name: Run CI checks
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
jobs:
  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/actions-setup@v4
        with:
          version: 10
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: cd backend && pnpm install --frozen-lockfile
      - name: Check linting
        run: cd backend && pnpm run lint
      - name: Check formatting
        run: cd backend && pnpm run prettier
      - name: Run test coverage
        run: cd backend && pnpm run test:coverage
      - name: Report results to DeepSource
        run: |
          curl https://deepsource.io/cli | sh
          ./bin/deepsource report --analyzer test-coverage --key javascript --value-file ./backend/coverage/cobertura-coverage.xml
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}

  frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/actions-setup-node@v4
        with:
          version: 10
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: cd frontend && pnpm install --frozen-lockfile
      - name: Check linting
        run: cd frontend && pnpm run lint
      - name: Check formatting
        run: cd frontend && pnpm run prettier
