name: Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy VisualEditor
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MEDIAWIKI_HOST }}
          key: ${{ secrets.WIKI_SSH_KEY }}
          username: ${{ secrets.WIKI_USERNAME }}
          script: |
            folder_path="/home/wiki/wikiadviser"
            canasta_path="/home/wiki/canasta"
            visual_editor_folder_name="MyVisualEditor"

            # Check if the folder exists
            if [ -d "$folder_path" ]; then
                echo "wikiadviser exists..."
                cd $folder_path
                git pull
            else
                echo "wikiadviser doesn't exist, Cloning Repo..."
                git clone git@github.com:ankaboot-source/wikiadviser.git
            fi

            cd $canasta_path; docker compose down
            mv $folder_path/$visual_editor_folder_name $canasta_path/extensions/$visual_editor_folder_name

            cd $canasta_path; docker compose up -d
