name: Deploy Supabase Prod functions

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SAAS_SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROD_PROJECT_ID }}
      WIKIADVISER_BACKGROUND_COLORS: ${{ vars.WIKIADVISER_BACKGROUND_COLORS }}
      WIKIADVISER_LANGUAGES: ${{ vars.WIKIADVISER_LANGUAGES }}
      WIKIPEDIA_PROXY: ${{ vars.WIKIPEDIA_PROXY }}
      MEDIAWIKI_ENDPOINT: ${{ vars.MEDIAWIKI_ENDPOINT_PROD }}
      MW_BOT_USERNAME: ${{ secrets.MW_BOT_USERNAME_PROD }}
      MW_BOT_PASSWORD: ${{ secrets.MW_BOT_PASSWORD_PROD }}
      WIKIADVISER_KEY: ${{ secrets.WIKIADVISER_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: link project
        run: supabase link --project-ref $SUPABASE_PROJECT_ID

      - name: set Supabase secrets
        run: supabase secrets set WIKIADVISER_BACKGROUND_COLORS="$WIKIADVISER_BACKGROUND_COLORS" WIKIADVISER_LANGUAGES="$WIKIADVISER_LANGUAGES" WIKIPEDIA_PROXY="$WIKIPEDIA_PROXY" MEDIAWIKI_ENDPOINT="$MEDIAWIKI_ENDPOINT" MW_BOT_USERNAME="$MW_BOT_USERNAME" MW_BOT_PASSWORD="$MW_BOT_PASSWORD" WIKIADVISER_KEY="$WIKIADVISER_KEY"

      - name: list Supabase secrets
        run: supabase secrets list

      - name: deploy restrict-mediawiki-access
        run: supabase functions deploy restrict-mediawiki-access --no-verify-jwt --debug

      - name: deploy share-link
        run: supabase functions deploy share-link --debug

      - name: deploy user-avatar
        run: supabase functions deploy user-avatar --debug

      - name: deploy wikipedia
        run: supabase functions deploy wikipedia --no-verify-jwt --debug

      - name: deploy article
        run: supabase functions deploy article --no-verify-jwt --debug
