name: Deploy Supabase QA functions
on:
  push:
    branches: [main]
    paths:
      - 'supabase/functions/**'
  workflow_dispatch:
jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SAAS_SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      WIKIADVISER_BACKGROUND_COLORS: "f6f8fa,ffffff"
      WIKIADVISER_LANGUAGES: "en,fr"
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: link project
        run: supabase link --project-ref $SUPABASE_PROJECT_ID

      - name: set Supabase secrets
        run: supabase secrets set WIKIADVISER_BACKGROUND_COLORS="$WIKIADVISER_BACKGROUND_COLORS" WIKIADVISER_LANGUAGES="$WIKIADVISER_LANGUAGES"

      - name: list Supabase secrets
        run: supabase secrets list

      - name: deploy share_links
        run: supabase functions deploy share_links --debug
        
      - name: deploy restrictMediawikiAccess
        run: supabase functions deploy restrictMediawikiAccess --no-verify-jwt --debug

      - name: deploy user-avatar
        run: supabase functions deploy  user-avatar --debug


