name: Keep Supabase Active

on:
  schedule:
    - cron: '0 0 */2 * *' # Runs every 2 days at 00:00
  workflow_dispatch:
jobs:
  keep-QA-active:
    runs-on: ubuntu-latest
    env:
      SUPABASE_SECRET_PROJECT_TOKEN: ${{ secrets.SUPABASE_SECRET_PROJECT_TOKEN }}

    steps:
      - name: Request QA Supabase to keep it alive
        run: |
          request() { curl -X GET "https://enxddisazdljwcvranya.supabase.co/rest/v1/profiles" -H "apikey: $SUPABASE_SECRET_PROJECT_TOKEN" -H "Authorization: Bearer $SUPABASE_SECRET_PROJECT_TOKEN"; }
          for i in {1..10}; do   request > /dev/null 2>&1;   echo "Next request will be in 3sec";   sleep 3; done

  keep-PROD-active:
    runs-on: ubuntu-latest
    env:
      SUPABASE_SECRET_PROJECT_TOKEN: ${{ secrets.SUPABASE_PROD_SECRET_PROJECT_TOKEN }}

    steps:
      - name: Request PROD Supabase to keep it alive
        run: |
          request() { curl -X GET "https://rcsxuyoogygnyjbwbrbb.supabase.co/rest/v1/profiles" -H "apikey: $SUPABASE_SECRET_PROJECT_TOKEN" -H "Authorization: Bearer $SUPABASE_SECRET_PROJECT_TOKEN"; }
          for i in {1..10}; do   request > /dev/null 2>&1;   echo "Next request will be in 3sec";   sleep 3; done
