name: Upgrade Mediawiki Environments

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to upgrade'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - prod

jobs:
  upgrade:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Upgrade environment
      uses: appleboy/ssh-action@master
      env:
        MW_SUDO_PWD: ${{ secrets.MW_SUDO_PWD }}
      with:
        host: ${{ vars.MEDIAWIKI_DEMO_HOST }}
        key: ${{ secrets.MEDIAWIKI_DEMO_PRIVATE_SSH }}
        username: ${{ secrets.MEDIAWIKI_DEMO_USERNAME }}
        envs: MW_SUDO_PWD
        script: |

          if [ "${{ github.event.inputs.environment }}" = "dev" ]; then
            environments=("dev")
          elif [ "${{ github.event.inputs.environment }}" = "qa" ]; then
            environments=("demo")
          elif [ "${{ github.event.inputs.environment }}" = "prod" ]; then
            environments=("prod")
          fi

          mediawiki_password="${MW_SUDO_PWD}"
          languages=("fr" "en")

          echo "Upgrading ${{ github.event.inputs.environment }} environment..."
          chmod +x /home/wiki-user/wikiadviser/mediawiki-setup/mediawiki-upgrade.sh
          export environments
          export languages
          export mediawiki_password
          bash -c 'source /home/wiki-user/wikiadviser/mediawiki-setup/mediawiki-upgrade.sh'
