name: Upgrade Mediawiki Environments

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to upgrade'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - prod

jobs:
  upgrade:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Upgrade environment
      uses: appleboy/ssh-action@master
      env:
        MW_SUDO_PWD: ${{ secrets.MW_SUDO_PWD }}
      with:
        host: ${{ vars.MEDIAWIKI_DEMO_HOST }}
        key: ${{ secrets.MEDIAWIKI_DEMO_PRIVATE_SSH }}
        username: ${{ secrets.MEDIAWIKI_DEMO_USERNAME }}
        script: |
          echo "Setting environment variables"
          export mediawiki_password="${MW_SUDO_PWD}"
          
          if [ "${{ github.event.inputs.environment }}" = "dev" ]; then
            environments=("dev")
          elif [ "${{ github.event.inputs.environment }}" = "qa" ]; then
            environments=("demo")
          elif [ "${{ github.event.inputs.environment }}" = "prod" ]; then
            environments=("prod")
          fi
          
          languages=("fr" "en")
          
          echo "Upgrading ${{ github.event.inputs.environment }} environment"
          echo "${MW_SUDO_PWD}" | sudo -S bash /home/wiki-user/wikiadviser/mediawiki-setup/mediawiki-upgrade.sh
