name: Deploy monitoring
on:
  push:
    branches: [main]
    paths:
      - 'monitoring-agent/**'
  workflow_dispatch:

jobs:
  deploy-monitoring-wikiadviser:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Deploy monitoring wikiadviser demo
        uses: appleboy/ssh-action@master
        env:
          LOKI_ENDPOINT: ${{ vars.LOKI_ENDPOINT }}
        with:
          host: ${{ vars.WIKIADVISER_DEMO_HOST }}
          key: ${{ secrets.SSH_PRIVATE_WIKIADVISER }}
          username: ${{ secrets.WIKIADVISER_USERNAME }}
          envs: LOKI_ENDPOINT
          script: |
            wikiadviser_path="/home/wikiadviser-user/wikiadviser"
            
            # Check if the folder exists
            if [ -d "$wikiadviser_path" ]; then
                echo "wikiadviser exists..."
            else
                echo "wikiadviser doesn't exist, Cloning Repo..."
                git clone git@github.com:ankaboot-source/wikiadviser.git $wikiadviser_path
            fi
            
            # pull changes         
            cd $wikiadviser_path/monitoring-agent; docker compose down; git pull;
            export LOKI_ENDPOINT
            envsubst < promtail-config.yaml.conf > promtail-config.yaml

            # Start monitoring exporters 
            docker compose up -d;

      - name: Deploy monitoring wikiadviser prod
        uses: appleboy/ssh-action@master
        env:
          LOKI_ENDPOINT: ${{ vars.LOKI_ENDPOINT }}
        with:
          host: ${{ vars.WIKIADVISER_PROD_HOST }}
          key: ${{ secrets.SSH_PRIVATE_WIKIADVISER_PROD }}
          username: ${{ secrets.SSH_USERNAME_WIKIADVISER_PROD }}
          envs: LOKI_ENDPOINT
          script: |
            wikiadviser_path="/home/wikiadviser-prod/wikiadviser"

            # Check if the folder exists
            if [ -d "$wikiadviser_path" ]; then
                echo "wikiadviser exists..."
            else
                echo "wikiadviser doesn't exist, Cloning Repo..."
                git clone git@github.com:ankaboot-source/wikiadviser.git $wikiadviser_path
            fi

            # pull changes         
            cd $wikiadviser_path/monitoring-agent; docker compose down; git pull;
            export LOKI_ENDPOINT
            envsubst < promtail-config.yaml.conf > promtail-config.yaml

            # Start monitoring exporters 
            docker compose up -d;


  deploy-monitoring-mediawiki:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Deploy monitoring mediawiki
        uses: appleboy/ssh-action@master
        env:
          LOKI_ENDPOINT: ${{ vars.LOKI_ENDPOINT }}
        with:
          host: ${{ vars.MEDIAWIKI_DEMO_HOST }}
          key: ${{ secrets.MEDIAWIKI_DEMO_PRIVATE_SSH }}
          username: ${{ secrets.MEDIAWIKI_DEMO_USERNAME }}
          envs: LOKI_ENDPOINT
          script: |
            wikiadviser_path="/home/wiki-user/wikiadviser"
            
            # Check if the folder exists
            if [ -d "$wikiadviser_path" ]; then
                echo "wikiadviser exists..."
            else
                echo "wikiadviser doesn't exist, Cloning Repo..."
                git clone git@github.com:ankaboot-source/wikiadviser.git $wikiadviser_path
            fi

            # pull changes         
            cd $wikiadviser_path/monitoring-agent; docker compose down; git pull;
            export LOKI_ENDPOINT
            envsubst < promtail-config.yaml.conf > promtail-config.yaml

            # Start monitoring exporters 
            docker compose up -d;
            docker stop monitoring-agent-cadvisor-1
            docker container prune
