name: "functions-tests"
on:
  pull_request:
    paths:
      - "supabase/functions/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - uses: denoland/setup-deno@v2
        with:
          deno-version: latest
      - run: supabase start
      - run: deno test supabase/functions --allow-all
