name: "functions-tests"
on:
  pull_request:
    paths:
      - "supabase/functions/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - uses: denoland/setup-deno@v2
        with:
          deno-version: latest
      - name: Run unit tests
        run: deno test supabase/functions --allow-all --coverage
      - name: Report code coverage to Deepsource
        run: |
          curl https://deepsource.io/cli | sh
          ./bin/deepsource report --analyzer test-coverage --key javascript --value-file ./coverage/*
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
