name: Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-wikiadviser:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Wikiadviser
        uses: appleboy/ssh-action@master
        env:
          SUPABASE_PROJECT_URL: ${{ secrets.SUPABASE_PROJECT_URL }}
          SUPABASE_SECRET_PROJECT_TOKEN: ${{ secrets.SUPABASE_SECRET_PROJECT_TOKEN }}
          WIKIADVISER_API_HOST: ${{ secrets.WIKIADVISER_API_HOST }}
          MEDIAWIKI_HOST: ${{ secrets.MEDIAWIKI_HOST }}
          WIKIADVISER_API_PORT: ${{ secrets.WIKIADVISER_API_PORT }}
        with:
          host: ${{ vars.WIKIADVISER_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.WIKIADVISER_USERNAME }}
          envs: WIKIADVISER_API_HOST,SUPABASE_SECRET_PROJECT_TOKEN,WIKIADVISER_API_HOST,MEDIAWIKI_HOST,WIKIADVISER_API_PORT
          script: |
            wikiadviser_path="/home/wikiadviser-user/wikiadviser"

            # Check if the folder exists
            if [ -d "$folder_path" ]; then
                echo "wikiadviser exists..."
                cd $folder_path
                git pull
            else
                echo "wikiadviser doesn't exist, Cloning Repo..."
                git clone git@github.com:ankaboot-source/wikiadviser.git $wikiadviser_path
            fi

            cd $wikiadviser_path; docker compose -f docker-compose.prod.yml down; git pull

            export WIKIADVISER_API_HOST
            export SUPABASE_SECRET_PROJECT_TOKEN
            export SUPABASE_PROJECT_URL
            export MEDIAWIKI_HOST
            export WIKIADVISER_API_PORT

            envsubst > $wikiadviser_path/.env

            docker compose --env-file .env -f docker-compose.prod.yml up -d \
              --build \
              --force-recreate

            #Remove unused images
            docker image prune -a -f

  deploy-visual-editor:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy VisualEditor
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.MEDIAWIKI_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.WIKI_USERNAME }}
          script: |
            folder_path="/home/wiki-user/wikiadviser"
            canasta_path="/home/wiki-user/canasta"
            visual_editor_folder_name="MyVisualEditor"

            # Check if the folder exists
            if [ -d "$folder_path" ]; then
                echo "wikiadviser exists..."
                cd $folder_path
                git pull
            else
                echo "wikiadviser doesn't exist, Cloning Repo..."
                git clone git@github.com:ankaboot-source/wikiadviser.git $folder_path
            fi

            cd $canasta_path; docker compose down
            mv $folder_path/$visual_editor_folder_name $canasta_path/extensions/$visual_editor_folder_name

            cd $canasta_path; docker compose up -d
