name: Deploy Prod
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  approval:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: baderdean,zieddhf,J43fura
          minimum-approvals: 1
          issue-title: "Deploy to Prod"
          issue-body: "Please approve or deny the deployment, comment LGTM! or approved to approve | deny or Denied! to deny"

  deploy-wikiadviser:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    needs: approval
    steps:
      - name: Deploy Wikiadviser Prod
        uses: appleboy/ssh-action@master
        env:
          SUPABASE_PROJECT_URL: ${{ secrets.SUPABASE_PROD_PROJECT_URL }}
          SUPABASE_SECRET_PROJECT_TOKEN: ${{ secrets.SUPABASE_PROD_SECRET_PROJECT_TOKEN }}
          WIKIADVISER_LANGUAGES: ${{ vars.WIKIADVISER_LANGUAGES }}
          SHARE_LINK_DAY_LIMIT: ${{ vars.SHARE_LINK_DAY_LIMIT }}
          MEDIAWIKI_ENDPOINT: ${{ vars.MEDIAWIKI_ENDPOINT_PROD }}
          WIKIADVISER_FRONTEND_ENDPOINT: ${{ vars.WIKIADVISER_FRONTEND_ENDPOINT }}
          NODE_ENV: ${{vars.NODE_ENV}}
          WIKIPEDIA_PROXY: ${{ vars.WIKIPEDIA_PROXY }}
          MEDIAWIKI_INTERNAL_ENDPOINT: ${{ vars.MEDIAWIKI_INTERNAL_ENDPOINT_PROD }}
          MW_BOT_USERNAME: ${{ secrets.MW_BOT_USERNAME_PROD }}
          MW_BOT_PASSWORD: ${{ secrets.MW_BOT_PASSWORD_PROD }}
          SENTRY_DSN_FRONTEND: ${{secrets.SENTRY_DSN_FRONTEND_PROD}}
          SENTRY_ENV_FRONTEND: ${{secrets.SENTRY_ENV_FRONTEND_PROD}}
          POSTHOG_API_KEY: ${{secrets.POSTHOG_API_KEY}}
          POSTHOG_API_HOST: ${{vars.POSTHOG_API_HOST}}
          X_API_KEY: ${{secrets.X_API_KEY_PROD}}

        with:
          host: ${{ vars.WIKIADVISER_PROD_HOST }}
          key: ${{ secrets.SSH_PRIVATE_WIKIADVISER_PROD }}
          username: ${{ secrets.SSH_USERNAME_WIKIADVISER_PROD }}
          envs: X_API_KEY,MEDIAWIKI_PROD_ENDPOINT,MEDIAWIKI_INTERNAL_ENDPOINT,SUPABASE_SECRET_PROJECT_TOKEN,MEDIAWIKI_ENDPOINT,SUPABASE_PROJECT_URL,WIKIPEDIA_PROXY,MW_BOT_USERNAME,MW_BOT_PASSWORD,SENTRY_DSN_FRONTEND,SENTRY_ENV_FRONTEND,WIKIADVISER_FRONTEND_ENDPOINT,WIKIADVISER_LANGUAGES,SHARE_LINK_DAY_LIMIT,NODE_ENV,POSTHOG_API_KEY,POSTHOG_API_HOST

          script: |
            wikiadviser_path="$HOME/wikiadviser"

            # Check if the folder exists
            if [ -d "$wikiadviser_path" ]; then
                echo "wikiadviser exists..."
                cd $wikiadviser_path
                git pull
            else
                echo "wikiadviser doesn't exist, Cloning Repo..."
                git clone git@github.com:ankaboot-source/wikiadviser.git $wikiadviser_path
            fi

            cd $wikiadviser_path; docker compose -f docker-compose.prod.yml down; git pull

            echo "SUPABASE_SECRET_PROJECT_TOKEN=$SUPABASE_SECRET_PROJECT_TOKEN" > $wikiadviser_path/.env
            echo "SUPABASE_PROJECT_URL=$SUPABASE_PROJECT_URL" >> $wikiadviser_path/.env
            echo "MEDIAWIKI_INTERNAL_ENDPOINT=$MEDIAWIKI_INTERNAL_ENDPOINT" >> $wikiadviser_path/.env
            echo "MEDIAWIKI_ENDPOINT=$MEDIAWIKI_ENDPOINT" >> $wikiadviser_path/.env
            echo "MW_BOT_USERNAME=$MW_BOT_USERNAME" >> $wikiadviser_path/.env
            echo "MW_BOT_PASSWORD=$MW_BOT_PASSWORD" >> $wikiadviser_path/.env
            echo "WIKIADVISER_LANGUAGES=$WIKIADVISER_LANGUAGES" >> $wikiadviser_path/.env
            echo "SHARE_LINK_DAY_LIMIT=$SHARE_LINK_DAY_LIMIT" >> $wikiadviser_path/.env
            echo "WIKIADVISER_FRONTEND_ENDPOINT=$WIKIADVISER_FRONTEND_ENDPOINT" >> $wikiadviser_path/.env
            echo "WIKIPEDIA_PROXY=$WIKIPEDIA_PROXY" >> $wikiadviser_path/.env
            echo "SENTRY_DSN_FRONTEND=$SENTRY_DSN_FRONTEND" >> $wikiadviser_path/.env
            echo "SENTRY_ENV_FRONTEND=$SENTRY_ENV_FRONTEND" >> $wikiadviser_path/.env
            echo "POSTHOG_API_KEY=$POSTHOG_API_KEY" >> $wikiadviser_path/.env
            echo "POSTHOG_API_HOST=$POSTHOG_API_HOST" >> $wikiadviser_path/.env
            echo "NODE_ENV=$NODE_ENV" >> $wikiadviser_path/.env
            echo "X_API_KEY=$X_API_KEY" >> $wikiadviser_path/.env

            docker compose --env-file .env -f docker-compose.prod.yml up -d \
              --build \
              --force-recreate

            # Remove unused images/containers/volumes
            docker system prune -f

  deploy-visual-editor-prod:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    strategy:
      matrix:
        lang: [fr, en]
        env: [prod]
    steps:
      - name: Deploy VisualEditor
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.MEDIAWIKI_DEMO_HOST }}
          key: ${{ secrets.MEDIAWIKI_DEMO_PRIVATE_SSH }}
          username: ${{ secrets.MEDIAWIKI_DEMO_USERNAME }}
          script: |
            wikiadviser_path="/home/wiki-user/wikiadviser"
            visual_editor_folder_name="MyVisualEditor"
            extensions_path="/home/wiki-user/wikiadviser/docker/resources/extensions"
            assets_path="/home/wiki-user/wikiadviser/docker/resources/assets/*"
            extensions_base_path="/var/www/wiki-${{ matrix.env }}"

            # Check if the folder exists
            if [ -d "$wikiadviser_path" ]; then
                echo "wikiadviser exists..."
                cd $wikiadviser_path
                git pull
            else
                echo "wikiadviser doesn't exist, Cloning Repo..."
                git clone git@github.com:ankaboot-source/wikiadviser.git $wikiadviser_path
            fi

            # Copy Visual Editor to Extensions
            cp -r $extensions_path/$visual_editor_folder_name /var/www/wiki-${{ matrix.env }}/wiki/${{ matrix.lang }}/extensions/

            # Copy assets
            cp -r $assets_path /var/www/wiki-${{ matrix.env }}/${{ matrix.lang }}/wiki/resources/assets/

            # Run update.php in Maintenance Folder
            # https://www.mediawiki.org/wiki/Manual:Update.php
            cd /var/www/wiki-${{ matrix.env }}/wiki/${{ matrix.lang }}/maintenance/
            php update.php --quick
