name: Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-wikiadviser:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Wikiadviser
        uses: appleboy/ssh-action@master
        env:
          SUPABASE_PROJECT_URL: ${{ secrets.SUPABASE_PROJECT_URL }}
          SUPABASE_SECRET_PROJECT_TOKEN: ${{ secrets.SUPABASE_SECRET_PROJECT_TOKEN }}

          WIKIADVISER_API_HOST: ${{ secrets.WIKIADVISER_API_HOST }}
          WIKIADVISER_API_PORT: ${{ secrets.WIKIADVISER_API_PORT }}
          WIKIADVISER_FRONTEND_HOST: ${{ vars.WIKIADVISER_FRONTEND_HOST }}

          WIKIPEDIA_PROXY: ${{ vars.WIKIPEDIA_PROXY }}

          MEDIAWIKI_HOST: ${{ secrets.MEDIAWIKI_HOST }}
          MW_ADMIN_USERNAME: ${{ secrets.MW_ADMIN_USERNAME }}
          MW_ADMIN_PASSWORD: ${{ secrets.MW_ADMIN_PASSWORD }}
          MW_BOT_USERNAME: ${{ secrets.MW_BOT_USERNAME }}
          MW_BOT_PASSWORD: ${{ secrets.MW_BOT_PASSWORD }}

        with:
          host: ${{ vars.WIKIADVISER_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.WIKIADVISER_USERNAME }}
          envs: WIKIADVISER_API_HOST,SUPABASE_SECRET_PROJECT_TOKEN,WIKIADVISER_API_HOST,MEDIAWIKI_HOST,SUPABASE_PROJECT_URL,WIKIADVISER_API_PORT,WIKIADVISER_FRONTEND_HOST,WIKIPEDIA_PROXY,MW_ADMIN_USERNAME,MW_ADMIN_PASSWORD,MW_BOT_USERNAME,MW_BOT_PASSWORD
          script: |
            wikiadviser_path="/home/wikiadviser-user/wikiadviser"
            
            # Check if the folder exists
            if [ -d "$wikiadviser_path" ]; then
                echo "wikiadviser exists..."
                cd $wikiadviser_path
                git pull
            else
                echo "wikiadviser doesn't exist, Cloning Repo..."
                git clone git@github.com:ankaboot-source/wikiadviser.git $wikiadviser_path
            fi

            cd $wikiadviser_path; docker compose -f docker-compose.prod.yml down; git pull

            echo "SUPABASE_SECRET_PROJECT_TOKEN=$SUPABASE_SECRET_PROJECT_TOKEN" > $wikiadviser_path/.env
            echo "SUPABASE_PROJECT_URL=$SUPABASE_PROJECT_URL" >> $wikiadviser_path/.env

            echo "MEDIAWIKI_HOST=$MEDIAWIKI_HOST" >> $wikiadviser_path/.env
            echo "MW_ADMIN_USERNAME=$MW_ADMIN_USERNAME" >> $wikiadviser_path/.env
            echo "MW_ADMIN_PASSWORD=$MW_ADMIN_PASSWORD" >> $wikiadviser_path/.env
            echo "MW_BOT_USERNAME=$MW_BOT_USERNAME" >> $wikiadviser_path/.env
            echo "MW_BOT_PASSWORD=$MW_BOT_PASSWORD" >> $wikiadviser_path/.env

            echo "WIKIADVISER_API_PORT=$WIKIADVISER_API_PORT" >> $wikiadviser_path/.env
            echo "WIKIADVISER_API_HOST=$WIKIADVISER_API_HOST" >> $wikiadviser_path/.env
            echo "WIKIADVISER_FRONTEND_HOST=$WIKIADVISER_FRONTEND_HOST" >> $wikiadviser_path/.env

            echo "WIKIPEDIA_PROXY=$WIKIPEDIA_PROXY" >> $wikiadviser_path/.env

            docker compose --env-file .env -f docker-compose.prod.yml up -d \
              --build \
              --force-recreate

            # Remove unused images/containers/volumes
            docker system prune -f

  deploy-visual-editor:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy VisualEditor
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.MEDIAWIKI_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.WIKI_USERNAME }}
          script: |
            folder_path="/home/wiki-user/wikiadviser"
            canasta_path="/home/wiki-user/canasta"
            visual_editor_folder_name="MyVisualEditor"

            # Check if the folder exists
            if [ -d "$folder_path" ]; then
                echo "wikiadviser exists..."
                cd $folder_path
                git pull
            else
                echo "wikiadviser doesn't exist, Cloning Repo..."
                git clone git@github.com:ankaboot-source/wikiadviser.git $folder_path
            fi

            cd $canasta_path; docker compose down
            rm -rf $canasta_path/extensions/$visual_editor_folder_name
            cp -rf $folder_path/$visual_editor_folder_name $canasta_path/extensions/$visual_editor_folder_name

            cd $canasta_path; docker compose up -d
