name: Deploy Demo
on:
  push:
    branches: [main]
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  deploy-wikiadviser:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Wikiadviser Demo
        uses: appleboy/ssh-action@master
        env:
          SUPABASE_PROJECT_URL: ${{ secrets.SUPABASE_QA_PROJECT_URL }}
          SUPABASE_SECRET_PROJECT_TOKEN: ${{ secrets.SUPABASE_QA_SECRET_PROJECT_TOKEN }}
          WIKIADVISER_LANGUAGES: ${{ vars.WIKIADVISER_LANGUAGES }}
          SHARE_LINK_DAY_LIMIT: ${{ vars.SHARE_LINK_DAY_LIMIT }}
          WIKIADVISER_API_PORT: ${{ vars.WIKIADVISER_API_PORT }}
          MEDIAWIKI_ENDPOINT: ${{ vars.MEDIAWIKI_ENDPOINT_QA }}
          WIKIADVISER_FRONTEND_ENDPOINT: ${{ vars.WIKIADVISER_FRONTEND_ENDPOINT_QA }}
          WIKIADVISER_API_ENDPOINT: ${{ vars.WIKIADVISER_API_ENDPOINT_QA }}
          NODE_ENV: ${{vars.NODE_ENV}}
          WIKIPEDIA_PROXY: ${{ vars.WIKIPEDIA_PROXY }}
          MEDIAWIKI_INTERNAL_ENDPOINT: ${{ vars.MEDIAWIKI_INTERNAL_ENDPOINT_QA }}
          MW_ADMIN_USERNAME: ${{ secrets.MW_ADMIN_USERNAME_QA }}
          MW_ADMIN_PASSWORD: ${{ secrets.MW_ADMIN_PASSWORD_QA }}
          MW_BOT_USERNAME: ${{ secrets.MW_BOT_USERNAME_QA }}
          MW_BOT_PASSWORD: ${{ secrets.MW_BOT_PASSWORD_QA }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN_QA }}
          SENTRY_ENV_BACKEND: ${{secrets.SENTRY_ENV_BACKEND_QA}}
          SENTRY_DSN_FRONTEND: ${{secrets.SENTRY_DSN_FRONTEND_QA}}
          SENTRY_ENV_FRONTEND: ${{secrets.SENTRY_ENV_FRONTEND_QA}}
          MEDIAWIKI_DEV_ENDPOINT: ${{vars.MEDIAWIKI_DEV_ENDPOINT}}

        with:
          host: ${{ vars.WIKIADVISER_DEMO_HOST }}
          key: ${{ secrets.SSH_PRIVATE_WIKIADVISER }}
          username: ${{ secrets.WIKIADVISER_USERNAME }}
          envs: MEDIAWIKI_DEV_ENDPOINT,MEDIAWIKI_ENDPOINT,MEDIAWIKI_INTERNAL_ENDPOINT,SUPABASE_SECRET_PROJECT_TOKEN,SUPABASE_PROJECT_URL,WIKIADVISER_API_PORT,WIKIPEDIA_PROXY,MW_ADMIN_USERNAME,MW_ADMIN_PASSWORD,MW_BOT_USERNAME,MW_BOT_PASSWORD,SENTRY_DSN,SENTRY_ENV_BACKEND,SENTRY_DSN_FRONTEND,SENTRY_ENV_FRONTEND,WIKIADVISER_FRONTEND_ENDPOINT,WIKIADVISER_API_ENDPOINT,WIKIADVISER_LANGUAGES,SHARE_LINK_DAY_LIMIT,NODE_ENV
          script: |
            wikiadviser_path="$HOME/wikiadviser"
            # Check if the folder exists
            if [ -d "$wikiadviser_path" ]; then
                echo "wikiadviser exists..."
                cd $wikiadviser_path
                git pull
            else
                echo "wikiadviser doesn't exist, Cloning Repo..."
                git clone git@github.com:ankaboot-source/wikiadviser.git $wikiadviser_path
            fi

            cd $wikiadviser_path; docker compose -f docker-compose.demo.yml down; git pull

            # Prepare .env file
            echo "SUPABASE_SECRET_PROJECT_TOKEN=$SUPABASE_SECRET_PROJECT_TOKEN" > $wikiadviser_path/.env
            echo "SUPABASE_PROJECT_URL=$SUPABASE_PROJECT_URL" >> $wikiadviser_path/.env
            echo "MEDIAWIKI_INTERNAL_ENDPOINT=$MEDIAWIKI_INTERNAL_ENDPOINT" >> $wikiadviser_path/.env
            echo "MEDIAWIKI_ENDPOINT=$MEDIAWIKI_ENDPOINT" >> $wikiadviser_path/.env
            echo "MW_ADMIN_USERNAME=$MW_ADMIN_USERNAME" >> $wikiadviser_path/.env
            echo "MW_ADMIN_PASSWORD=$MW_ADMIN_PASSWORD" >> $wikiadviser_path/.env
            echo "MW_BOT_USERNAME=$MW_BOT_USERNAME" >> $wikiadviser_path/.env
            echo "MW_BOT_PASSWORD=$MW_BOT_PASSWORD" >> $wikiadviser_path/.env
            echo "WIKIADVISER_LANGUAGES=$WIKIADVISER_LANGUAGES" >> $wikiadviser_path/.env
            echo "SHARE_LINK_DAY_LIMIT=$SHARE_LINK_DAY_LIMIT" >> $wikiadviser_path/.env
            echo "WIKIADVISER_API_PORT=$WIKIADVISER_API_PORT" >> $wikiadviser_path/.env
            echo "WIKIADVISER_API_ENDPOINT=$WIKIADVISER_API_ENDPOINT" >> $wikiadviser_path/.env
            echo "WIKIADVISER_FRONTEND_ENDPOINT=$WIKIADVISER_FRONTEND_ENDPOINT" >> $wikiadviser_path/.env
            echo "WIKIPEDIA_PROXY=$WIKIPEDIA_PROXY" >> $wikiadviser_path/.env
            echo "SENTRY_DSN=$SENTRY_DSN" >> $wikiadviser_path/.env
            echo "SENTRY_ENV_BACKEND=$SENTRY_ENV_BACKEND" >> $wikiadviser_path/.env
            echo "SENTRY_DSN_FRONTEND=$SENTRY_DSN_FRONTEND" >> $wikiadviser_path/.env
            echo "SENTRY_ENV_FRONTEND=$SENTRY_ENV_FRONTEND" >> $wikiadviser_path/.env
            echo "NODE_ENV=$NODE_ENV" >> $wikiadviser_path/.env
            echo "MEDIAWIKI_DEV_ENDPOINT=$MEDIAWIKI_DEV_ENDPOINT" >> $wikiadviser_path/.env

            docker compose --env-file .env -f docker-compose.demo.yml up -d \
              --build \
              --force-recreate

            #Remove unused images/containers/volumes
            docker system prune -f

  deploy-visual-editor-demo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lang: [fr, en]
        env: [dev, demo]
    steps:
      - name: Deploy VisualEditor
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.MEDIAWIKI_DEMO_HOST }}
          key: ${{ secrets.MEDIAWIKI_DEMO_PRIVATE_SSH }}
          username: ${{ secrets.MEDIAWIKI_DEMO_USERNAME }}
          script: |
            wikiadviser_path="/home/wiki-user/wikiadviser"
            visual_editor_folder_name="MyVisualEditor"
            assets_folder="/docs/assets/*"
            extensions_base_path="/var/www/wiki-${{ matrix.env }}"
            
            # Check if the folder exists
            if [ -d "$wikiadviser_path" ]; then
                echo "wikiadviser exists..."
                cd $wikiadviser_path
                git pull
            else
                echo "wikiadviser doesn't exist, Cloning Repo..."
                git clone git@github.com:ankaboot-source/wikiadviser.git $wikiadviser_path
            fi
           
            # Copy Visual Editor to Extensions
            cp -r $wikiadviser_path/$visual_editor_folder_name /var/www/wiki-${{ matrix.env }}/wiki/${{ matrix.lang }}/extensions/

            # Copy assets
            cp -r $wikiadviser_path/$assets_folder /var/www/wiki-${{ matrix.env }}/wiki/${{ matrix.lang }}/resources/assets/

            # Run update.php in Maintenance Folder
            # https://www.mediawiki.org/wiki/Manual:Update.php
            cd /var/www/wiki-${{ matrix.env }}/wiki/${{ matrix.lang }}/maintenance/
            php update.php --quick
